### ISSUE TITLE
7.0.0 fails to lint Styled Components

### ISSUE THREAD

**Issue by johnnybenson** [stylelint/stylelint-config-recommended#156]
### What steps are needed to reproduce the bug?

Upgrade 7.0.0 and run the linter

### What did you expect to happen?

Passes

### What actually happened?

Fails

----

The introduction of the rule `function-no-unknown` breaks for styled components because of the wild ass syntax of Styled Components.

**Comment by johnnybenson** [comment]
```js
module.exports = {
    extends: [
        'stylelint-config-recommended',
        'stylelint-config-styled-components',
    ],
    overrides: [
        {
            files: ['**/*.tsx'],
            customSyntax: '@stylelint/postcss-css-in-js',
        },
    ],
    rules: {
        'function-no-unknown': undefined,
    },
};
```

If anyone wants to turn this off across their project

**Comment by jeddy3** [comment]
@johnnybenson Thanks for the report.

The official configs, like Stylelint itself, are designed for standard CSS files.

> If anyone wants to turn this off across their project

You are correct to extend the config and then turn off the rule for custom syntax. I suggest turning the rule off inside of `overrides` so that things are kept together and that the config can be applied to CSS files too:

```js
module.exports = {
    extends: [
        'stylelint-config-recommended',
        'stylelint-config-styled-components',
    ],
    overrides: [
        {
            files: ['**/*.tsx'],
            customSyntax: '@stylelint/postcss-css-in-js',
            rules: {
               'function-no-unknown': null,
            },
        },
    ], 
};
```
