### ISSUE TITLE
Update peerDependencies to match current stylelint

### ISSUE THREAD

**Issue by toptalo** [stylelint/stylelint-config-recommended#32]
Get warning:
```
npm WARN stylelint-config-recommended@2.1.0 requires a peer of stylelint
@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependenc
ies yourself.
```

- stylelint-config-recommended@2.1.0
- stylelint@9.5.0

**Comment by jeddy3** [comment]
@toptalo Thanks for the report.

I'm not sure why you got that warning because `9.5.0` [is within](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) the `^9.0.0` _range_.

It might of been a npm install glitch. I'll close the issue for now, but feel free to reopen it if the message reoccurs with a clean `npm install`.
